### ISSUE TITLE
switch connection to mainnet

### ISSUE THREAD

**Issue by sdbarrington** [danmt/wallet-adapter-angular-sample#1]
hey, awesome work on this! 

Is there an easy way to switch the connection from devnet to mainnet? I can't seem to get it to work.

**Comment by sdbarrington** [comment]
ok think I got it working ;)
```
//set mainnet
this._connectionStore.setEndpoint('https://api.mainnet-beta.solana.com');
```

**Comment by danmt** [comment]
Glad you made it!
