### ISSUE TITLE
Updated sample to work with newest version?

### ISSUE THREAD

**Issue by rmdorsey** [danmt/wallet-adapter-angular-sample#2]
Hey, this library is great!  I was able to get it working and I'm using it to work through the solana tutorials (but in angular of course).  I noticed that this example is not using the most up to date version of your library.  Do you have one that you can upload?  Thank you!

**Comment by danmt** [comment]
Hey @rmdorsey, yeah, the `base` adapter changed a few days back and I didn't know. I'll try to update it this weekend, it should be pretty straightforward.

**Comment by danmt** [comment]
I updated pretty much every dependency and it's now working up to date. One thing tho, it was decided to extract the Angular Adapter out from Solana's repo, the same will happen with other core adapters like Svelte. This will make things more decentralized and will help us iterate faster. I suppose this will be announced later on.

You can find the wallet-adapter:

- [GitHub](https://github.com/heavy-duty/platform/tree/master/libs/shared/wallet-adapter)
- [NPM](https://www.npmjs.com/package/@heavy-duty/wallet-adapter)

I'll close this issue for now.

**Comment by rmdorsey** [comment]
Thank you @danmt !   Works great in your example app, however, when I try to use the library in my application I'm getting the following errors when I try to import any of the wallet adapters...

<img width="1221" alt="Screen Shot 2022-02-02 at 12 32 12 AM" src="https://user-images.githubusercontent.com/16293510/152105601-45fb31a4-41e0-431a-aba1-7b7dc588b468.png">

**Comment by andresmgsl** [comment]
Hey @rmdorsey , I havent been able to reproduce the issue, is it possible for you to share your repo or create a reproduction repo ?

**Comment by rmdorsey** [comment]
> Hey @rmdorsey , I havent been able to reproduce the issue, is it possible for you to share your repo or create a reproduction repo ?

Yes, sorry.  Here's the repo: https://github.com/rmdorsey/web3_angular13_seed/tree/web3

If you clone it down it'll compile, but as soon as you import the wallet adapters you'll see the issue I described.  See app.component.ts where I have commented out the wallet adapter imports.
