### ISSUE TITLE
NX Cannot find project 'web-client'

### ISSUE THREAD

**Issue by smacrineanu** [danmt/wallet-adapter-angular-sample#5]
I have cloned this repository and tried serving it as per documentation:

```
C:\Dev\wallet-adapter-angular-sample> npx nx serve web-client

 >  NX   Cannot find project 'web-client'
```

**Comment by danmt** [comment]
Hi there, this README was autogenerated, for updated docs you can visit https://github.com/heavy-duty/platform/tree/master/libs/wallet-adapter/data-access
